# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0004_auto_20170221_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarschedule',
            name='event',
            field=models.CharField(choices=[('dawn_astronomical', 'dawn_astronomical'), ('dawn_nautical', 'dawn_nautical'), ('dawn_civil', 'dawn_civil'), ('sunrise', 'sunrise'), ('solar_noon', 'solar_noon'), ('sunset', 'sunset'), ('dusk_civil', 'dusk_civil'), ('dusk_nautical', 'dusk_nautical'), ('dusk_astronomical', 'dusk_astronomical')], max_length=24, verbose_name='event'),
        ),
    ]
